// config.js
export const CONFIG = {
  TUNNEL: {
    RADIUS: 2000,
    SEGMENTS: 700,
    TUBE_RADIUS: 210,
    TUBE_SEGMENTS: 120,
    TUBE_RADIAL_SEGMENTS: 12,
    SPEED: 220,
    ROLL_AMOUNT: 0.95,
    COLOR_BASE_HUE: 0.52,
    COLOR_PULSE_RANGE: 0.12,
    VERTICAL_WAVE_SPEED: 1.2,
    VERTICAL_WAVE_AMPLITUDE: 6,
  },

  SHIP: {
    WIDTH: 200,
    HEIGHT: 100,
    SPEED: 5,             
    ACCELERATION: 2400,   // px/s² 
    DAMPING: 0.85,        // HIGHER = SPACE ICE
    MAX_OFFSET_X: 400,
    MAX_OFFSET_Y: 250,
    ROTATION_SMOOTHING: 0.15,
    TILT_ANGLE: 30, // DEGREES
    FRAME_INTERPOLATION_ACTIVE: 0.25,
    FRAME_INTERPOLATION_IDLE: 0.08,
    SPRITE_FRAMES: 5, // 0=UP, 1=HALF-UP, 2=NEUTRAL, 3=HALF-DOWN, 4=DOWN
    NEUTRAL_FRAME: 2,
    UP_FRAME: 0,
    DOWN_FRAME: 4,
  },

  BARREL_ROLL: {
    DURATION: 0.6, // SECONDS
    PARTICLE_SPAWN_MULTIPLIER: 2,
  },

  PARTICLES: {
    MAX_COUNT: 30,
    SPAWN_RATE: 3,
    LIFE_MIN: 0.5,
    LIFE_VARIANCE: 0.15,
    RADIUS: 30,
    VELOCITY_X_RANGE: 40,
    VELOCITY_Y_BASE: 20,
    VELOCITY_Y_VARIANCE: 90,
    SPAWN_SPREAD: 20,
    OPACITY: 0, // SETTING TO 0 WHILE I WORK ON MECHANICS
    COLOR_PRIMARY: '#00ffff',
    COLOR_SECONDARY: '#8C92AC',
  },

  SCENE: {
    FOG_DENSITY: 0.00075,
    BACKGROUND_COLOR: 0x0a0015,
    CAMERA_FOV: 75,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 5000,
  },

  MOBILE: {
    JOYSTICK_RADIUS: 60,
    DEAD_ZONE: 15,
  },

  MAX_PIXEL_RATIO: 2,

  ENEMIES: {
    MAX_COUNT: 5,
    SPAWN_INTERVAL_MIN: 3.0, 
    SPAWN_INTERVAL_MAX: .0,
    SPAWN_DISTANCE: 300, 
    
    
    SPRITE_PATH: './images/glitches.png',
    SPRITE_FRAMES: 15,       // TOTAL FRAMES IN SHEET
    SPRITE_SIZE: 80,

  
    FRAME_RANGES: {
      TANK:   { start: 8, count: 3 },
      BASIC:  { start: 0, count: 4 },
      FAST:   { start: 4, count: 4 },
      ZIGZAG: { start: 11, count: 4 },
    },

    // HOW FAST EACH TYPE CYCLES FRAMES 
    ANIM_SPEEDS: {
      TANK:   7,   
      BASIC:  9,  
      FAST:   12, 
      ZIGZAG: 9,  
    },
    
   
    TYPES: {
      BASIC: {
        SIZE: 40,
        SPEED: 180, 
        COLOR: '#ff00ff',
        GLOW_COLOR: '#ff00ff',
        HEALTH: 1,
        SCORE: 10,
      },
      FAST: {
        SIZE: 30,
        SPEED: 300,
        COLOR: '#ff3366',
        GLOW_COLOR: '#ff3366',
        HEALTH: 1,
        SCORE: 20,
      },
      TANK: {
        SIZE: 60,
        SPEED: 120,
        COLOR: '#ff9900',
        GLOW_COLOR: '#ffaa00',
        HEALTH: 3,
        SCORE: 50,
      },
      ZIGZAG: {
        SIZE: 35,
        SPEED: 200,
        COLOR: '#00ff88',
        GLOW_COLOR: '#00ff88',
        HEALTH: 1,
        SCORE: 30,
        ZIGZAG_AMPLITUDE: 80,
        ZIGZAG_FREQUENCY: 3,
      },
    },
    
   
    GLOW_OPACITY: 0.3,
    GLOW_SCALE: 1.4,
    PULSE_SPEED: 2.5,
    TRAIL_ENABLED: true,
    TRAIL_PARTICLE_RATE: 0.1, 
  },

  SHOOTING: {
    FIRE_RATE: 0.15, 
    PROJECTILE_SPEED: 1200, 
    PROJECTILE_SIZE: 8,
    PROJECTILE_LENGTH: 30,
    PROJECTILE_COLOR: '#00ffff',
    PROJECTILE_GLOW_COLOR: '#00ffff',
    MAX_PROJECTILES: 50,
    
    CROSSHAIR_SPRITE: './images/crosshair.png',
    CROSSHAIR_SIZE: 60,
    CROSSHAIR_FRAMES: 3,               // SPRITE SHEET: 0=NORMAL(PURPLE), 1=RED(LOCK), 2=YELLOW(LOCK)
    CROSSHAIR_AIM_DEFLECT_PX: 260,    // MAX px FROM CENTER — CROSSHAIR RANGE OF MOTION
    CROSSHAIR_OFFSET_MULTIPLIER: 0.55, // FALLBACK
    CROSSHAIR_CENTER_PULL: 0.35,       // 0=NONE, 1=LOCKED TO CENTER
    CROSSHAIR_INNER_LAG: 0.22,         // LOWER = MORE LAG
    CROSSHAIR_INPUT_SMOOTHING: 0.03,   // LOWER = FLOATIER
    CROSSHAIR_OUTER_LAG: 0.11,         // OUTER BRACKETS CHASE SPEED 
    CROSSHAIR_MAX_SEPARATION: 55,      // MAX PIXEL DISTANCE BETWEEN INNER AND OUTER RETICLES
    CROSSHAIR_OUTER_SCALE: 1.5,        // OUTER BRACKETS - SIZE RELATIVE TO INNER SPRITE 
    CROSSHAIR_LOCK_RADIUS_MULTIPLIER: 0.6,
    CROSSHAIR_FLASH_SPEED: 0.08,

    // MOUSE AIM 
    MOUSE_AIM_MAX_RADIUS: 320,         
    
    FLASH_SPRITE: './images/flash.png',
    FLASH_FRAMES: 2,
    FLASH_DURATION: 0.1, 
    FLASH_SIZE: 50,
  },

  EXPLOSIONS: {
    SPRITE: './images/boom.png',
    FRAMES: 6,
    FRAME_DURATION: 0.05, 
    SIZE: 150,
  },
};