// config.js
export const CONFIG = {
  TUNNEL: {
    RADIUS: 2400, 
    SEGMENTS: 700,
    TUBE_RADIUS: 330, 
    TUBE_SEGMENTS: 120,
    TUBE_RADIAL_SEGMENTS: 12,
    SPEED: 210,
    ROLL_AMOUNT: 0.95,
    COLOR_BASE_HUE: 0.7, 
    COLOR_PULSE_RANGE: 0.07, 
    VERTICAL_WAVE_SPEED: 0.5,
    VERTICAL_WAVE_AMPLITUDE: 0, // 0 DURING NNORMAL GAME PLAY
  },

  SHIP: {
    WIDTH: 180,
    HEIGHT: 160,
    SPEED: 5,             
    ACCELERATION: 2400,   // px/sÃ‚Â² 
    DAMPING: 0.85,        // HIGHER = SPACE ICE
    MAX_OFFSET_X: 400,
    MAX_OFFSET_Y: 250,
    ROTATION_SMOOTHING: 0.15,
    TILT_ANGLE: 30, 
    FRAME_INTERPOLATION_ACTIVE: 0.25,
    FRAME_INTERPOLATION_IDLE: 0.08,
    SPRITE_FRAMES: 5, // 0=UP, 1=HALF-UP, 2=NEUTRAL, 3=HALF-DOWN, 4=DOWN
    NEUTRAL_FRAME: 2,
    UP_FRAME: 0,
    DOWN_FRAME: 4,
  },

  BARREL_ROLL: {
    DURATION: 0.6, 
    PARTICLE_SPAWN_MULTIPLIER: 2,
  },

  PARTICLES: {
    MAX_COUNT: 30,
    SPAWN_RATE: 3,
    LIFE_MIN: 0.5,
    LIFE_VARIANCE: 0.15,
    RADIUS: 30,
    VELOCITY_X_RANGE: 40,
    VELOCITY_Y_BASE: 20,
    VELOCITY_Y_VARIANCE: 90,
    SPAWN_SPREAD: 20,
    OPACITY: 0, // SETTING TO 0 WHILE I WORK ON MECHANICS
    COLOR_PRIMARY: '#00ffff',
    COLOR_SECONDARY: '#8C92AC',
  },

  SCENE: {
    FOG_DENSITY: 0.00069, 
    BACKGROUND_COLOR: 0x0a0015,
    CAMERA_FOV: 75,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 5000,
  },

  MOBILE: {
    JOYSTICK_RADIUS: 60,
    DEAD_ZONE: 15,
  },

  MAX_PIXEL_RATIO: 2,

  ENEMIES: {
    MAX_COUNT: 5, 
    SPAWN_INTERVAL_MIN: 2.0, 
    SPAWN_INTERVAL_MAX: 5.5,
    SPAWN_DISTANCE: 400, 
    SPRITE_SIZE: 180,

    COMBAT_SCALE:      0.82,  // SCALE THRESHOLD — APPROACH → COMBAT TRANSITION
    COMBAT_RING_ALPHA: 0.28,  // TIMEOUT RING OPACITY

    TYPES: {
      BASIC: { // GLIP GLOP
        SIZE: 40,
        SPEED: 180,
        COLOR: '#FF0000',
        GLOW_COLOR: '#FF0000',
        HEALTH: 5,
        SCORE: 10,
        SPRITE_FRAMES: 5,
        ANIM_SPEED: 9,
        COLLISION_DAMAGE: 20,
        LASER_COLOR: '#FF0000',
        LASER_INTERVAL: 3.2,
        COMBAT_DURATION: 9.0,  
        WANDER_SPEED: 70,
        WANDER_X: 180,
        WANDER_Y: 120,
      },
      FAST: { // ZIP ZAP
        SIZE: 30,
        SPEED: 300,
        COLOR: '#ff3366',
        GLOW_COLOR: '#ff3366',
        HEALTH: 5,
        SCORE: 20,
        SPRITE_FRAMES: 6,
        ANIM_SPEED: 12,
        COLLISION_DAMAGE: 20,
        LASER_COLOR: '#FF0000',
        LASER_INTERVAL: 2.0,    
        COMBAT_DURATION: 7.0,   
        WANDER_SPEED: 200,
        WANDER_X: 290,
        WANDER_Y: 170,
      },
      TANK: { // GLORK
        SIZE: 60,
        SPEED: 70,
        COLOR: '#FF0000',
        GLOW_COLOR: '#FF0000',
        HEALTH: 10,
        SCORE: 50,
        SPRITE_FRAMES: 5,
        ANIM_SPEED: 7,
        COLLISION_DAMAGE: 35,
        LASER_COLOR: '#ff0000',
        LASER_INTERVAL: 3.5,
        COMBAT_DURATION: 16.0,  
        WANDER_SPEED: 30,
        WANDER_X: 90,
        WANDER_Y: 60,
      },
      ZIGZAG: { // PHIL
        SIZE: 35,
        SPEED: 200,
        COLOR: '#FF0000',
        GLOW_COLOR: '#FF0000',
        HEALTH: 7,
        SCORE: 30,
        ZIGZAG_AMPLITUDE: 90,
        ZIGZAG_FREQUENCY: 3.2,
        SPRITE_FRAMES: 8,
        ANIM_SPEED: 9,
        COLLISION_DAMAGE: 20,
        LASER_COLOR: '#FF0000',
        LASER_INTERVAL: 2.8,
        COMBAT_DURATION: 11.0,
        WANDER_SPEED: 55,       
        WANDER_X: 80,
        WANDER_Y: 130,
      },
      FLIMFLAM: { // FLIM FLAM — THE BUZZER
        SIZE: 38,
        SPEED: 260,
        COLOR: '#FF0000',
        GLOW_COLOR: '#FF0000',
        HEALTH: 7,
        SCORE: 40,
        SPRITE_FRAMES: 8,       // TOTAL: 3 WING + 1 RED EYE + 4 BODY
        WING_FRAMES: 3,         // FRAMES 0-2
        RED_EYE_FRAME: 3,       // FRAME 3
        BODY_FRAMES: 4,         // FRAMES 4-7
        BODY_FRAME_OFFSET: 4,   // DRAW OFFSET: 4
        WING_ANIM_SPEED: 16,
        ANIM_SPEED: 6,
        COLLISION_DAMAGE: 20,
        LASER_COLOR: '#FF0000',
        LASER_INTERVAL: 2.8,
        HOVER_DURATION_MIN: 0.7,
        HOVER_DURATION_MAX: 1.6,
        DASH_SPEED: 420,
        BOB_AMPLITUDE: 6,
        BOB_SPEED: 4.5,
        ROAM_X: 240,
        ROAM_Y: 155,
        COMBAT_DURATION: 11.0,
        // OCULAR PRISM ATTACK
        PRISM_FIRST_DELAY_MIN: 3.0, 
        PRISM_FIRST_DELAY_MAX: 5.5,
        PRISM_COOLDOWN_MIN:    8.0,  
        PRISM_COOLDOWN_MAX:   12.0,
        PRISM_TELEGRAPH:       1.8,  
      },
    },

    GLOW_OPACITY: 0.3,
    GLOW_SCALE: 1.4,
    PULSE_SPEED: 2.5,
    TRAIL_ENABLED: true,
    TRAIL_PARTICLE_RATE: 0.1,
  },

  SHOOTING: {
    FIRE_RATE: 0.15, 
    PROJECTILE_SPEED: 1200, 
    PROJECTILE_SIZE: 8,
    PROJECTILE_LENGTH: 30,
    PROJECTILE_COLOR: '#00ffff',
    PROJECTILE_GLOW_COLOR: '#00ffff',
    MAX_PROJECTILES: 50,
    
    CROSSHAIR_SIZE: 60,
    CROSSHAIR_AIM_DEFLECT_PX: 500,    // MAX px FROM CENTER Ã¢â‚¬â€ CROSSHAIR RANGE OF MOTION
    CROSSHAIR_OFFSET_MULTIPLIER: 0.55,
    CROSSHAIR_CENTER_PULL: 0.35,       // 0=NONE, 1=LOCKED TO CENTER
    CROSSHAIR_INNER_LAG: 0.22,         // LOWER = MORE LAG
    CROSSHAIR_INPUT_SMOOTHING: 0.03,   // LOWER = FLOATIER
    CROSSHAIR_OUTER_LAG: 0.11,         // OUTER BRACKETS CHASE SPEED 
    CROSSHAIR_MAX_SEPARATION: 55,      // MAX PIXEL DISTANCE BETWEEN INNER AND OUTER RETICLES
    CROSSHAIR_OUTER_SCALE: 1.5,        // OUTER BRACKETS - SIZE RELATIVE TO INNER SPRITE 
    CROSSHAIR_LOCK_RADIUS_MULTIPLIER: 0.6,
    CROSSHAIR_FLASH_SPEED: 0.08,

    FLASH_DURATION: 0.1, 
  },

  // ======================= SHIP HP & LIVES =======================
  SHIP_HP: {
    MAX_HP:                  100,
    MAX_LIVES:               3,
    INVINCIBILITY_DURATION:  2.0,   
    INVINCIBILITY_FLASH_HZ:  8,     // FLASHES PER SECOND WHILE INVINCIBLE
    SUCTION_DEATH_SCALE:     0.18,  // SUCTIONSCALE BELOW THIS = FULLY CONSUMED — LOSE A LIFE
    RESPAWN_INVINCIBILITY:   3.0,  
    DAMAGE_SUCKED_IN:        100,   
  },

  // ======================= WORM SUCTION PHYSICS =======================
  WORM_SUCTION: { // FORCE PROFILE
    BASE_FORCE:        600,    // px/s² at max distance  
    RAMP_EXPONENT:     1.8,    // HOW AGGRESSIVELY FORCE GROWS AS SHIP GETS CLOSER (>1 = exponential ramp)
    MAX_FORCE:         3200,   // HARD CAP — PREVENTS INSTANT VACUUM
    MAX_DISTANCE:      900,    // BEYOND THIS DISTANCE: ZERO SUCTION FORCE
    SPIN_STRENGTH:     0.55,   // TANGENTIAL FORCE MULTIPLIER (sideways pull)
    PULL_STRENGTH:     1.0,    // RADIAL FORCE MULTIPLIER (straight-in pull)
    // BARREL ROLL COUNTER
    ROLL_SPIN_RESIST:  0.06,   // SPIRAL REDUCED TO THIS FRACTION WHILE ROLLING
    ROLL_PULL_RESIST:  0.40,   // RADIAL REDUCED TO THIS FRACTION WHILE ROLLING
    ROLL_BURST_FORCE:  900,    // OUTWARD BURST AT ROLL PEAK (progress ~0.5) 
    // VISUAL SCALE — SHIP SHRINKS AS IT GETS SUCKED IN
    SCALE_NEAR:        0.05,   // SMALLEST SCALE AT MOUTH — MUST BE BELOW SUCTION_DEATH_SCALE
    SCALE_FAR:         1.0,    // NORMAL SCALE AT MAX_DISTANCE
    SCALE_LERP:        0.06,   // HOW FAST SCALE RECOVERS / RESPONDS
    SHAKE_INTENSITY:   4,      // px
    // CLAMP EXPANSION — SUCTION CAN PULL SHIP PAST NORMAL PLAY FIELD
    MAX_OFFSET_EXPAND: 1.6,    // MULTIPLIER ON NORMAL MAX_OFFSET DURING ATTACK
  },

  ENEMY_LASER: {
    SPEED:          480,    
    DAMAGE:         15,
    HIT_RADIUS:     14,    
    BOLT_LENGTH:    22,     
    BOLT_WIDTH:     3,
    GLOW_BLUR:      12,
    FIRST_SHOT_MIN: 1.0,
    FIRST_SHOT_MAX: 2.5,
  },

EXPLOSIONS: {
    BAM_FRAMES:     8,
    BAM_SIZE:       160,
    BOOM_FRAMES:    6,
    BOOM_SIZE:      200,
    FRAME_DURATION: 0.03,
  },

  // ======================= BABY WORM ATTACK =======================
  BABY_WORM: {
    SPRITE_PATH:         './images/babyWorm.png',
    SPRITE_FRAMES:       2,
    HEAD_SIZE:           80,
    SEGMENT_SIZE_RATIO:  1,
    NUM_SEGMENTS:        6,
    SEGMENT_SPACING:     11,

    SPAWN_COUNT:         5,
    SPAWN_INTERVAL:      0.30,

    SEEK_SPEED:          175,
    SEEK_ACCEL:          55,
    MAX_SPEED:           310,
    WIGGLE_AMP:          38,
    WIGGLE_FREQ:         3.8,

    LATCH_RADIUS:        38,
    LATCH_ORBIT_SPEED:   0.9,
    LATCH_ORBIT_DIST:    52,
    LATCH_DAMAGE_RATE:   8,

    TRAIL_LENGTH:        40,
    TRAIL_COLOR:         '#55ff88',
    TRAIL_GLOW:          '#00ff44',
    TRAIL_MAX_SIZE:      13,
    TRAIL_MIN_SIZE:      2,
    TRAIL_MAX_ALPHA:     0.65,

    ATTACK_DURATION:     9.0,
  },

  SLIME_ATTACK: {
    FIRST_ATTACK_MIN:   1.0,   
    FIRST_ATTACK_MAX:   1.5, 
    REPEAT_INTERVAL:    22.0,  
    MIN_SCALE:           0.50,  // GLORK MUST BE THIS SIZE TO ATTACK
    TUNNEL_SPEED_MULT:   0.28,  // TUNNEL SLOWS TO THIS PERCENT OF NORMAL SPEED 
    TUNNEL_GREEN:       0x22ff44, 

    TRAIL_MAX:           10,    // TRACERS
    TRAIL_CAPTURE_RATE:  0.055, // SECONDS BETWEEN SNAPSHOTS
    
    CONTROL_ACCEL_MULT:  0.45, // MOLLASSES PHYSICS 
    CONTROL_DAMP_MULT:   0.60, 
  },

  OCULAR_PRISM: {
    DURATION:       14.0,   
    FADE_DURATION:   0.6,   

    SHARD_MIN:       3,     
    SHARD_MAX:       5,     

    PUPIL_RADIUS:   44,     
    PUPIL_HEALTH:    3,    

    ICHOR_COUNT:    55,     

    PUPIL_HIT_SCORE: 25,    
    PUPIL_KILL_SCORE: 200,  
  },
};