// config.js
export const CONFIG = {
  TUNNEL: {
    RADIUS: 2400, 
    SEGMENTS: 700,
    TUBE_RADIUS: 330, 
    TUBE_SEGMENTS: 120,
    TUBE_RADIAL_SEGMENTS: 12,
    SPEED: 210,
    ROLL_AMOUNT: 0.95,
    COLOR_BASE_HUE: 0.7, 
    COLOR_PULSE_RANGE: 0.07, 
    VERTICAL_WAVE_SPEED: 0.5,
    VERTICAL_WAVE_AMPLITUDE: 0, // 0 DURING NNORMAL GAME PLAY
  },

  SHIP: {
    WIDTH: 220,
    HEIGHT: 200,
    SPEED: 5,             
    ACCELERATION: 2400,   // px/sÃ‚Â² 
    DAMPING: 0.85,        // HIGHER = SPACE ICE
    MAX_OFFSET_X: 400,
    MAX_OFFSET_Y: 250,
    ROTATION_SMOOTHING: 0.15,
    TILT_ANGLE: 30, 
    FRAME_INTERPOLATION_ACTIVE: 0.25,
    FRAME_INTERPOLATION_IDLE: 0.08,
    SPRITE_FRAMES: 5, // 0=UP, 1=HALF-UP, 2=NEUTRAL, 3=HALF-DOWN, 4=DOWN
    NEUTRAL_FRAME: 2,
    UP_FRAME: 0,
    DOWN_FRAME: 4,
  },

  BARREL_ROLL: {
    DURATION: 0.6, 
    PARTICLE_SPAWN_MULTIPLIER: 2,
  },

  PARTICLES: {
    MAX_COUNT: 30,
    SPAWN_RATE: 3,
    LIFE_MIN: 0.5,
    LIFE_VARIANCE: 0.15,
    RADIUS: 30,
    VELOCITY_X_RANGE: 40,
    VELOCITY_Y_BASE: 20,
    VELOCITY_Y_VARIANCE: 90,
    SPAWN_SPREAD: 20,
    OPACITY: 0, // SETTING TO 0 WHILE I WORK ON MECHANICS
    COLOR_PRIMARY: '#00ffff',
    COLOR_SECONDARY: '#8C92AC',
  },

  SCENE: {
    FOG_DENSITY: 0.00069, 
    BACKGROUND_COLOR: 0x0a0015,
    CAMERA_FOV: 75,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 5000,
  },

  MOBILE: {
    JOYSTICK_RADIUS: 60,
    DEAD_ZONE: 15,
  },

  MAX_PIXEL_RATIO: 2,

  ENEMIES: {
    MAX_COUNT: 5, 
    SPAWN_INTERVAL_MIN: 4.0, 
    SPAWN_INTERVAL_MAX: 5.0,
    SPAWN_DISTANCE: 300, 
    SPRITE_SIZE: 180,

   
    TYPES: {
      BASIC: { // GLORK
        SIZE: 40,
        SPEED: 180, 
        COLOR: '#ff00ff',
        GLOW_COLOR: '#ff00ff',
        HEALTH: 1,
        SCORE: 10,
        SPRITE_FRAMES: 5, 
        ANIM_SPEED: 9
      },
      FAST: { // ZIP ZAP
        SIZE: 30,
        SPEED: 300,
        COLOR: '#ff3366',
        GLOW_COLOR: '#ff3366',
        HEALTH: 1,
        SCORE: 20,
        SPRITE_FRAMES: 6, 
        ANIM_SPEED: 12
      },
      TANK: { // PHIL
        SIZE: 60,
        SPEED: 120,
        COLOR: '#ff9900',
        GLOW_COLOR: '#ffaa00',
        HEALTH: 3,
        SCORE: 50,
        SPRITE_FRAMES: 8, 
        ANIM_SPEED: 7
      },
      ZIGZAG: { // GLIP GLOP AND GLITCH
        SIZE: 35,
        SPEED: 200,
        COLOR: '#00ff88',
        GLOW_COLOR: '#00ff88',
        HEALTH: 1,
        SCORE: 30,
        ZIGZAG_AMPLITUDE: 80,
        ZIGZAG_FREQUENCY: 3,
        SPRITE_FRAMES: 5, 
        ANIM_SPEED: 9
      },
    },
    
   
    GLOW_OPACITY: 0.3,
    GLOW_SCALE: 1.4,
    PULSE_SPEED: 2.5,
    TRAIL_ENABLED: true,
    TRAIL_PARTICLE_RATE: 0.1, 
  },

  SHOOTING: {
    FIRE_RATE: 0.15, 
    PROJECTILE_SPEED: 1200, 
    PROJECTILE_SIZE: 8,
    PROJECTILE_LENGTH: 30,
    PROJECTILE_COLOR: '#00ffff',
    PROJECTILE_GLOW_COLOR: '#00ffff',
    MAX_PROJECTILES: 50,
    
    CROSSHAIR_SIZE: 60,
    CROSSHAIR_AIM_DEFLECT_PX: 500,    // MAX px FROM CENTER Ã¢â‚¬â€ CROSSHAIR RANGE OF MOTION
    CROSSHAIR_OFFSET_MULTIPLIER: 0.55,
    CROSSHAIR_CENTER_PULL: 0.35,       // 0=NONE, 1=LOCKED TO CENTER
    CROSSHAIR_INNER_LAG: 0.22,         // LOWER = MORE LAG
    CROSSHAIR_INPUT_SMOOTHING: 0.03,   // LOWER = FLOATIER
    CROSSHAIR_OUTER_LAG: 0.11,         // OUTER BRACKETS CHASE SPEED 
    CROSSHAIR_MAX_SEPARATION: 55,      // MAX PIXEL DISTANCE BETWEEN INNER AND OUTER RETICLES
    CROSSHAIR_OUTER_SCALE: 1.5,        // OUTER BRACKETS - SIZE RELATIVE TO INNER SPRITE 
    CROSSHAIR_LOCK_RADIUS_MULTIPLIER: 0.6,
    CROSSHAIR_FLASH_SPEED: 0.08,

    FLASH_DURATION: 0.1, 
  },

  // ======================= SHIP HP & LIVES =======================
  SHIP_HP: {
    MAX_HP:                  100,
    MAX_LIVES:               3,
    INVINCIBILITY_DURATION:  2.0,   
    INVINCIBILITY_FLASH_HZ:  8,     
    SUCTION_DEATH_SCALE:     0.18,  // SUCTIONSCALE BELOW THIS = FULLY CONSUMED — LOSE A LIFE
    RESPAWN_INVINCIBILITY:   3.0,  
    DAMAGE_SUCKED_IN:        100,   
  },

  // ======================= WORM SUCTION PHYSICS =======================
  WORM_SUCTION: { // FORCE PROFILE
    BASE_FORCE:        600,    // px/s² at max distance  
    RAMP_EXPONENT:     1.8,    // HOW AGGRESSIVELY FORCE GROWS AS SHIP GETS CLOSER (>1 = exponential ramp)
    MAX_FORCE:         3200,   // HARD CAP — PREVENTS INSTANT VACUUM
    MAX_DISTANCE:      900,    // BEYOND THIS DISTANCE: ZERO SUCTION FORCE
    SPIN_STRENGTH:     0.55,   // TANGENTIAL FORCE MULTIPLIER (sideways pull)
    PULL_STRENGTH:     1.0,    // RADIAL FORCE MULTIPLIER (straight-in pull)
    ROLL_SPIN_RESIST:  0.06,   // SPIRAL REDUCED TO THIS FRACTION WHILE ROLLING
    ROLL_PULL_RESIST:  0.40,   // RADIAL REDUCED TO THIS FRACTION WHILE ROLLING
    ROLL_BURST_FORCE:  900,    // OUTWARD BURST AT ROLL PEAK (progress ~0.5) 
    SCALE_NEAR:        0.05,   
    SCALE_FAR:         1.0,    
    SCALE_LERP:        0.06,   // HOW FAST SCALE RECOVERS / RESPONDS
    SHAKE_INTENSITY:   4,      
    MAX_OFFSET_EXPAND: 1.6,    // MULTIPLIER ON NORMAL MAX_OFFSET DURING ATTACK
  },

EXPLOSIONS: {
    BAM_FRAMES:     8,
    BAM_SIZE:       150,
    BOOM_FRAMES:    6,
    BOOM_SIZE:      250,

    FRAME_DURATION: 0.03,
  },

  // ======================= BABY WORM ATTACK =======================
  BABY_WORM: {
    SPRITE_PATH:         './images/babyWorm.png',
    SPRITE_FRAMES:       2,
    HEAD_SIZE:           80,
    SEGMENT_SIZE_RATIO:  1,
    NUM_SEGMENTS:        6,
    SEGMENT_SPACING:     11,

    SPAWN_COUNT:         5,
    SPAWN_INTERVAL:      0.30,

    SEEK_SPEED:          175,
    SEEK_ACCEL:          55,
    MAX_SPEED:           310,
    WIGGLE_AMP:          38,
    WIGGLE_FREQ:         3.8,

    LATCH_RADIUS:        38,
    LATCH_ORBIT_SPEED:   0.9,
    LATCH_ORBIT_DIST:    52,
    LATCH_DAMAGE_RATE:   8,

    TRAIL_LENGTH:        40,
    TRAIL_COLOR:         '#55ff88',
    TRAIL_GLOW:          '#00ff44',
    TRAIL_MAX_SIZE:      13,
    TRAIL_MIN_SIZE:      2,
    TRAIL_MAX_ALPHA:     0.65,

    ATTACK_DURATION:     9.0,
  },
};